/**
 * V10 AGENT REGISTRY
 * 
 * acts as the "AST extracted" map of available agents in the system.
 * In a future iteration, this could be auto-generated by a build script.
 */

export interface AgentProfile {
  id: string;
  role: string;
  capabilities: string[];
  tier: 'free' | 'premium';
  icon: string;
}

export const SYSTEM_AGENTS: AgentProfile[] = [
  {
    id: 'captain-picard',
    role: 'Planner',
    capabilities: ['strategy', 'delegation', 'ethics'],
    tier: 'premium',
    icon: '🧑‍✈️'
  },
  {
    id: 'science-officer',
    role: 'Retrieval',
    capabilities: ['rag', 'vector-search', 'fact-checking'],
    tier: 'free',
    icon: '🧠'
  },
  {
    id: 'engineer-laforge',
    role: 'Worker',
    capabilities: ['code-execution', 'api-calls', 'troubleshooting'],
    tier: 'free',
    icon: '🛠'
  },
  {
    id: 'counselor-troi',
    role: 'Evaluator',
    capabilities: ['sentiment-analysis', 'safety-check', 'user-empathy'],
    tier: 'premium',
    icon: '⚖️'
  }
];

export function getAgentById(id: string) {
  return SYSTEM_AGENTS.find(a => a.id === id);
}
