/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-agent-registry.ts
 */

export interface AgentProfile {
  id: string;
  role: string;
  capabilities: string[];
  tier: 'free' | 'premium' | 'standard' | 'budget' | 'ultra_budget';
  icon: string;
}

export const SYSTEM_AGENTS: AgentProfile[] = [
  {
    "id": "base",
    "name": "BaseAgent",
    "role": "Worker",
    "capabilities": [
      "detected-via-cli"
    ],
    "tier": "free",
    "icon": "🛠"
  },
  {
    "id": "captain_picard",
    "name": "Captain Jean-Luc Picard",
    "role": "Strategic Leadership",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "premium",
    "icon": "🧑‍✈️"
  },
  {
    "id": "commander_data",
    "name": "Commander Data",
    "role": "Data Analytics",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "standard",
    "icon": "🧠"
  },
  {
    "id": "commander_riker",
    "name": "Commander William Riker",
    "role": "Tactical Execution",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "standard",
    "icon": "🛠"
  },
  {
    "id": "counselor_troi",
    "name": "Counselor Deanna Troi",
    "role": "User Experience",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "standard",
    "icon": "📡"
  },
  {
    "id": "lt_worf",
    "name": "Lieutenant Worf",
    "role": "Security Compliance",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "standard",
    "icon": "🛡"
  },
  {
    "id": "dr_crusher",
    "name": "Dr. Beverly Crusher",
    "role": "System Health",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "standard",
    "icon": "🧠"
  },
  {
    "id": "geordi_la_forge",
    "name": "Lt. Cmdr. Geordi La Forge",
    "role": "Infrastructure",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "standard",
    "icon": "🛠"
  },
  {
    "id": "lt_uhura",
    "name": "Lieutenant Uhura",
    "role": "Communications",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "standard",
    "icon": "📡"
  },
  {
    "id": "quark",
    "name": "Quark",
    "role": "Business Intelligence",
    "capabilities": [
      "shared-crew-member"
    ],
    "tier": "budget",
    "icon": "💰"
  }
];

export function getAgentById(id: string) {
  return SYSTEM_AGENTS.find(a => a.id === id);
}

export function getAgentsByRole(role: string) {
  return SYSTEM_AGENTS.filter(a => a.role === role);
}
