packages:
  # Unified Dashboard (Entry Point)
  - 'apps/*'

  # Shared Domain (Core Infrastructure)
  - 'domains/shared/crew-coordination'
  - 'domains/shared/cost-tracking'
  - 'domains/shared/schemas'
  - 'domains/shared/workflows'
  - 'domains/shared/ui-components'
  - 'domains/shared/openrouter-client'

  # DJ-Booking Domain
  - 'domains/dj-booking/dashboard'

  # Product Factory Domain
  - 'domains/product-factory/dashboard'

  # Alex-AI-Universal Domain
  - 'domains/alex-ai-universal/dashboard'
