/**
 * Database Types
 *
 * This file will be auto-generated by running:
 *   pnpm --filter @openrouter-crew/shared-schemas generate
 *
 * For now, here are the core type definitions based on the unified schema
 */
export {};
//# sourceMappingURL=database.js.map