import { z } from 'zod';

/**
 * Standard mission status levels following the Dark Forest Protocol.
 */
export const MissionStatusSchema = z.enum([
  'INITIATED',
  'IN_PROGRESS',
  'COMPLETED',
  'FAILED',
  'ABORTED'
]);

/**
 * Individual step within a mission plan.
 */
export const MissionStepSchema = z.object({
  step: z.number(),
  action: z.string(),
  agent: z.string(),
  status: z.enum(['pending', 'running', 'completed', 'failed']).default('pending'),
  result: z.any().optional(),
});

/**
 * The architectural brief generated by the PromptManager/Orchestrator.
 */
export const MissionBriefSchema = z.object({
  agentId: z.string(),
  agentPersona: z.string(),
  selectedModel: z.string(),
  refinedPrompt: z.string(),
  complexity: z.enum(['LOW', 'MEDIUM', 'HIGH']),
  originalPrompt: z.string().optional(),
});

/**
 * The full state of a project mission stored in Redis.
 */
export const MissionStateSchema = z.object({
  missionId: z.string(),
  projectId: z.string(),
  status: MissionStatusSchema,
  brief: MissionBriefSchema,
  steps: z.array(MissionStepSchema).default([]),
  timestamp: z.string().datetime(),
  error: z.string().optional(),
});

export type MissionState = z.infer<typeof MissionStateSchema>;