#!/usr/bin/env node

/**
 * Upload Crew Knowledge to Supabase
 * 
 * Reads the JSON file generated by scrape_memory_alpha.py and uploads
 * the records (including embeddings) to the crew_knowledge table.
 */

const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Load environment variables
const projectRoot = path.resolve(__dirname, '../../');
dotenv.config({ path: path.join(projectRoot, '.env.local') });

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('❌ Error: Missing Supabase credentials in .env.local');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);
const INPUT_FILE = path.join(projectRoot, 'data/knowledge/crew_memory_alpha.json');

async function uploadKnowledge() {
  if (!fs.existsSync(INPUT_FILE)) {
    console.error(`❌ Input file not found: ${INPUT_FILE}`);
    return;
  }

  const data = JSON.parse(fs.readFileSync(INPUT_FILE, 'utf8'));
  console.log(`📦 Found ${data.length} records to upload...`);

  let successCount = 0;
  let failCount = 0;

  for (const record of data) {
    const { crew_member, topic, content, skills, source_url, embedding } = record;

    const { error } = await supabase
      .from('crew_knowledge')
      .upsert({
        crew_member,
        topic,
        content,
        skills,
        source_url,
        embedding: embedding || null,
        last_updated: new Date().toISOString()
      });

    if (error) {
      console.error(`  ❌ Failed to upload ${crew_member}: ${error.message}`);
      failCount++;
    } else {
      console.log(`  ✅ Uploaded: ${crew_member}`);
      successCount++;
    }
  }

  console.log(`\n✨ Upload complete. Success: ${successCount}, Failed: ${failCount}`);
}

uploadKnowledge();