/**
 * Database Types
 *
 * This file will be auto-generated by running:
 *   pnpm --filter @openrouter-crew/shared-schemas generate
 *
 * For now, here are the core type definitions based on the unified schema
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type ProjectType = 'dj-booking' | 'product-factory' | 'ai-assistant' | 'custom';
export type ProjectStatus = 'draft' | 'active' | 'paused' | 'completed' | 'archived';
export type Provider = 'openrouter' | 'anthropic' | 'openai' | 'gemini';
export type RoutingMode = 'premium' | 'standard' | 'budget' | 'ultra_budget';
export type CostTier = 'premium' | 'standard' | 'budget' | 'ultra_budget';
export type MemoryType = 'observation' | 'decision' | 'learning' | 'context';
export type WorkflowType = 'crew' | 'system' | 'coordination' | 'project-specific' | 'subflow';
export type WorkflowStatus = 'running' | 'success' | 'failed' | 'timeout';

export interface Database {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          name: string;
          description: string | null;
          type: ProjectType;
          status: ProjectStatus;
          owner_id: string | null;
          team_members: string[];
          config: Json;
          metadata: Json;
          budget_usd: number | null;
          total_cost_usd: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          description?: string | null;
          type: ProjectType;
          status?: ProjectStatus;
          owner_id?: string | null;
          team_members?: string[];
          config?: Json;
          metadata?: Json;
          budget_usd?: number | null;
          total_cost_usd?: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string;
          description?: string | null;
          type?: ProjectType;
          status?: ProjectStatus;
          owner_id?: string | null;
          team_members?: string[];
          config?: Json;
          metadata?: Json;
          budget_usd?: number | null;
          total_cost_usd?: number;
        };
      };
      llm_usage_events: {
        Row: {
          id: string;
          created_at: string;
          project_id: string | null;
          workflow_id: string | null;
          crew_member: string | null;
          provider: Provider;
          model: string;
          input_tokens: number | null;
          output_tokens: number | null;
          total_tokens: number | null;
          estimated_cost_usd: number | null;
          actual_cost_usd: number | null;
          routing_mode: RoutingMode | null;
          request_type: string | null;
          metadata: Json;
          workflow: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          project_id?: string | null;
          workflow_id?: string | null;
          crew_member?: string | null;
          provider: Provider;
          model: string;
          input_tokens?: number | null;
          output_tokens?: number | null;
          total_tokens?: number | null;
          estimated_cost_usd?: number | null;
          actual_cost_usd?: number | null;
          routing_mode?: RoutingMode | null;
          request_type?: string | null;
          metadata?: Json;
          workflow?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          project_id?: string | null;
          workflow_id?: string | null;
          crew_member?: string | null;
          provider?: Provider;
          model?: string;
          input_tokens?: number | null;
          output_tokens?: number | null;
          total_tokens?: number | null;
          estimated_cost_usd?: number | null;
          actual_cost_usd?: number | null;
          routing_mode?: RoutingMode | null;
          request_type?: string | null;
          metadata?: Json;
          workflow?: string | null;
        };
      };
      crew_members: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          name: string;
          display_name: string;
          role: string;
          default_model: string;
          cost_tier: CostTier;
          webhook_url: string | null;
          active: boolean;
          workload_current: number;
          workload_capacity: number;
          avatar_url: string | null;
          bio: string | null;
          expertise: string[];
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          display_name: string;
          role: string;
          default_model?: string;
          cost_tier?: CostTier;
          webhook_url?: string | null;
          active?: boolean;
          workload_current?: number;
          workload_capacity?: number;
          avatar_url?: string | null;
          bio?: string | null;
          expertise?: string[];
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string;
          display_name?: string;
          role?: string;
          default_model?: string;
          cost_tier?: CostTier;
          webhook_url?: string | null;
          active?: boolean;
          workload_current?: number;
          workload_capacity?: number;
          avatar_url?: string | null;
          bio?: string | null;
          expertise?: string[];
        };
      };
      crew_memories: {
        Row: {
          id: string;
          created_at: string;
          project_id: string | null;
          crew_member: string;
          memory_type: MemoryType | null;
          content: string;
          tags: string[];
          importance: number;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          project_id?: string | null;
          crew_member: string;
          memory_type?: MemoryType | null;
          content: string;
          tags?: string[];
          importance?: number;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          project_id?: string | null;
          crew_member?: string;
          memory_type?: MemoryType | null;
          content?: string;
          tags?: string[];
          importance?: number;
          expires_at?: string | null;
        };
      };
      workflows: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          n8n_workflow_id: string | null;
          name: string;
          type: WorkflowType | null;
          webhook_path: string | null;
          active: boolean;
          config: Json;
          execution_count: number;
          total_cost_usd: number;
          last_executed_at: string | null;
          description: string | null;
          tags: string[];
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          n8n_workflow_id?: string | null;
          name: string;
          type?: WorkflowType | null;
          webhook_path?: string | null;
          active?: boolean;
          config?: Json;
          execution_count?: number;
          total_cost_usd?: number;
          last_executed_at?: string | null;
          description?: string | null;
          tags?: string[];
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          n8n_workflow_id?: string | null;
          name?: string;
          type?: WorkflowType | null;
          webhook_path?: string | null;
          active?: boolean;
          config?: Json;
          execution_count?: number;
          total_cost_usd?: number;
          last_executed_at?: string | null;
          description?: string | null;
          tags?: string[];
        };
      };
      workflow_executions: {
        Row: {
          id: string;
          created_at: string;
          completed_at: string | null;
          workflow_id: string | null;
          project_id: string | null;
          status: WorkflowStatus;
          duration_ms: number | null;
          error: string | null;
          tokens_used: number | null;
          estimated_cost_usd: number | null;
          input: Json | null;
          output: Json | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          completed_at?: string | null;
          workflow_id?: string | null;
          project_id?: string | null;
          status?: WorkflowStatus;
          duration_ms?: number | null;
          error?: string | null;
          tokens_used?: number | null;
          estimated_cost_usd?: number | null;
          input?: Json | null;
          output?: Json | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          completed_at?: string | null;
          workflow_id?: string | null;
          project_id?: string | null;
          status?: WorkflowStatus;
          duration_ms?: number | null;
          error?: string | null;
          tokens_used?: number | null;
          estimated_cost_usd?: number | null;
          input?: Json | null;
          output?: Json | null;
        };
      };
    };
    Views: {
      project_cost_summary: {
        Row: {
          id: string | null;
          name: string | null;
          type: ProjectType | null;
          status: ProjectStatus | null;
          budget_usd: number | null;
          total_cost_usd: number | null;
          total_requests: number | null;
          total_tokens: number | null;
          budget_used_percent: number | null;
        };
      };
      crew_workload_summary: {
        Row: {
          name: string | null;
          display_name: string | null;
          role: string | null;
          cost_tier: CostTier | null;
          active: boolean | null;
          projects_served: number | null;
          total_requests: number | null;
          total_cost_usd: number | null;
          total_tokens: number | null;
        };
      };
    };
  };
}
